/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.DB;
import db.DbConnectionData;
import db.DbException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.ContaDao;
import model.dao.TransacaoDao;
import model.entities.Conta;
import view.listeners.DataChangeListener;

/**
 *
 * @author danilodsf
 */
public class FrmCriarConta extends javax.swing.JFrame {
    
    private List<DataChangeListener> dataChangeListeners = new ArrayList<>();
    
    private DbConnectionData connData = null;
    
    public void subscribeDataChangeListener(DataChangeListener listener) {
        dataChangeListeners.add(listener);
    }

    /**
     * Creates new form frmCriarConta
     */
    public FrmCriarConta(DbConnectionData connData) {
        this.connData = connData;
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        tblContas.setRowSorter(new TableRowSorter(modelo));
        readTblContas();
    }
    
    private void readTblContas() {
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        modelo.setNumRows(0);
        ContaDao dao = new ContaDao(DB.getConnection(connData));
        
        try {
            for (Conta obj : dao.findAll()) {
                modelo.addRow(new Object[] {
                    obj.getId(),
                    obj.getDescricao()
                });
            }
        }
        catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar contas:\n" + e.getMessage());
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contas");
        setResizable(false);

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO"
            }
        ));
        tblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContas);

        jLabel1.setText("Descrição");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/edit.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/remove.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Contas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescricao)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String descricao = txtDescricao.getText();
        Conta obj = new Conta(null, descricao);
        
        ContaDao dao = new ContaDao(DB.getConnection(connData));
        try {
            dao.insert(obj);
            notifyDataChangeListeners();
            JOptionPane.showMessageDialog(null, "Conta criada com sucesso!");
            readTblContas();
            txtDescricao.setText("");
        }
        catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao criar conta:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void notifyDataChangeListeners() {
        for (DataChangeListener listener : dataChangeListeners) {
            listener.onDataChanged();
        }
    }
    
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (tblContas.getSelectedRow() != -1) {
            Conta obj = new Conta();
            ContaDao dao = new ContaDao(DB.getConnection(connData));
            
            obj.setId((int) tblContas.getValueAt(tblContas.getSelectedRow(), 0));
            obj.setDescricao(txtDescricao.getText());
            
            try {
                dao.update(obj);
                notifyDataChangeListeners();
                JOptionPane.showMessageDialog(null, "Conta atualizada com sucesso!");
                readTblContas();
                txtDescricao.setText("");
            }
            catch (DbException e) {
                JOptionPane.showMessageDialog(null, "Erro ao atualizar conta:\n" + e.getMessage());
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Nenhuma conta selecionada!");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContasMouseClicked
        if (tblContas.getSelectedRow() != -1) {
            txtDescricao.setText(tblContas.getValueAt(tblContas.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tblContasMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblContas.getSelectedRow() != -1) {
            int id = (int) tblContas.getValueAt(tblContas.getSelectedRow(), 0);
            ContaDao dao = new ContaDao(DB.getConnection(connData));
            
            if (!(dao.hasExistingMovements(id))) {
                try {
                    dao.deleteById(id);
                    notifyDataChangeListeners();
                    JOptionPane.showMessageDialog(null, "Conta excluída com sucesso!");
                    readTblContas();
                    txtDescricao.setText("");
                }
                catch (DbException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir conta:\n" + e.getMessage());
                }
            }
            else {
                int response = JOptionPane.showConfirmDialog(null, "Esta conta possui transações.\nAo exclui-la, você excluirá, também, essas transações.\nDeseja continuar?", "Excluir conta?", JOptionPane.YES_NO_OPTION);
                
                if (response == JOptionPane.YES_OPTION) {
                    TransacaoDao transacaoDao = new TransacaoDao(DB.getConnection(connData));
                    
                    try {
                        transacaoDao.deleteByContaId(id);
                        dao.deleteById(id);
                        notifyDataChangeListeners();
                        JOptionPane.showMessageDialog(null, "Conta e transações excluídas com sucesso!");
                        readTblContas();
                        txtDescricao.setText("");
                    }
                    catch (DbException e) {
                        JOptionPane.showMessageDialog(null, "Erro ao excluir conta:\n" + e.getMessage());
                    }
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Nenhuma conta selecionada!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCriarConta(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContas;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables

}
